### PR TITLE
Add option to make a Lad drink 3 after striking a center nail

### PR DESCRIPTION
**Pull request by seanKenkeremath**

### CODE REVIEW

**Review by austenlux-telus — APPROVED** [review]
🍺🍺🍺

**Review by austenlux — APPROVED** [review]

**Comment by mrketchup** [comment]
Should we limit the amount a lord can give a single lad to prevent trolling? I would absolutely do a triple flip and give @austenlux 9 drinks.

**Comment by seankenkeremath-stripe** [comment]
> Should we limit the amount a lord can give a single lad to prevent trolling? I would absolutely do a triple flip and give @austenlux 9 drinks.

Nah, that seems fine to me

**Comment by seanKenkeremath** [comment]
> Should we limit the amount a lord can give a single lad to prevent trolling? I would absolutely do a triple flip and give @austenlux 9 drinks.

Nah, that seems fine to me

**Review by mrketchup — APPROVED** [review]

**Pull request merged**
